# amr_controller.yaml (수정된 버전)

controller_manager:
  ros__parameters:
    update_rate: 30

    # Declares the controllers that the controller manager will load
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Parameters for the Joint Trajectory Controller
joint_trajectory_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true

    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
      wheel_left_joint:
        trajectory: 0.1
        goal: 0.1
      wheel_right_joint:
        trajectory: 0.1
        goal: 0.1

    # --- 이 부분이 추가되었습니다 ---
    gains:
      wheel_left_joint:
        p: 0.0
        i: 0.0
        d: 0.0
        ff_velocity_scale: 1.0
      wheel_right_joint:
        p: 0.0
        i: 0.0
        d: 0.0
        ff_velocity_scale: 1.0